server:
  port: 9001
  servlet:
    context-path: /demoAuth
spring:
  application:
    name: demo-auth
  profiles:
    active: @spring.profiles.active@

  redis:
    host: localhost
    port: 6379
    password: root
    timeout: 5000


  datasource:
    name: mydb
    url: ${jdbc.url}
    username: ${jdbc.username}
    password: ${jdbc.password}
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: ${jdbc.driverClassName}


auth:
  #token存储到redis的过期时间
  tokenValiditySeconds: 1200
  clientId: XcWebApp
  clientSecret: XcWebApp
  cookieDomain: localhost
  cookieMaxAge: -1



#构建数据对象映射文件
mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.example.demo.model


ribbon:
  MaxAutoRetries: 2 #最大重试次数，当Eureka中可以找到服务，但是服务连不上时将会重试，如果eureka中找不到服务则直接走断路器
  MaxAutoRetriesNextServer: 3 #切换实例的重试次数
  OkToRetryOnAllOperations: false  #对所有操作请求都进行重试，如果是get则可以，如果是post，put等操作没有实现幂等的情况下是很危险的,所以设置为false
  ConnectTimeout: 5000  #请求连接的超时时间
  ReadTimeout: 6000 #请求处理的超时时间